In [11]:
import polars as pl
print(pl.__version__)

1.43.1

In [12]:
import xy

In [13]:
df = pl.read_csv("https://github.com/jay-stein/chaddy-parking-scraper/blob/master/data/parking.csv?raw=true")

In [14]:
df.head(5)

shape: (5, 6)
┌─────────────────────┬──────────┬──────────┬────────┬────────────────┬──────────────┐
│ retrieved_at        ┆ car_park ┆ occupied ┆ vacant ┆ total_occupied ┆ total_vacant │
│ ---                 ┆ ---      ┆ ---      ┆ ---    ┆ ---            ┆ ---          │
│ str                 ┆ str      ┆ i64      ┆ i64    ┆ i64            ┆ i64          │
╞═════════════════════╪══════════╪══════════╪════════╪════════════════╪══════════════╡
│ 2026-07-12 14:44:24 ┆ B        ┆ 986      ┆ 94     ┆ 7745           ┆ 1499         │
│ 2026-07-12 14:44:24 ┆ F        ┆ 1305     ┆ 241    ┆ 7745           ┆ 1499         │
│ 2026-07-12 14:44:24 ┆ E        ┆ 1130     ┆ 215    ┆ 7745           ┆ 1499         │
│ 2026-07-12 14:44:24 ┆ A        ┆ 2605     ┆ 620    ┆ 7745           ┆ 1499         │
│ 2026-07-12 14:44:24 ┆ C        ┆ 1719     ┆ 329    ┆ 7745           ┆ 1499         │
└─────────────────────┴──────────┴──────────┴────────┴────────────────┴──────────────┘

In [15]:
df = (df
.with_columns(pl.col("retrieved_at")
.str.strptime(pl.Datetime, "%Y-%m-%d %H:%M:%S")
.alias("retrieved_at"))
)

In [16]:
df.filter(pl.col("car_park") == "B")

shape: (1_183, 6)
┌─────────────────────┬──────────┬──────────┬────────┬────────────────┬──────────────┐
│ retrieved_at        ┆ car_park ┆ occupied ┆ vacant ┆ total_occupied ┆ total_vacant │
│ ---                 ┆ ---      ┆ ---      ┆ ---    ┆ ---            ┆ ---          │
│ datetime[μs]        ┆ str      ┆ i64      ┆ i64    ┆ i64            ┆ i64          │
╞═════════════════════╪══════════╪══════════╪════════╪════════════════╪══════════════╡
│ 2026-07-12 14:44:24 ┆ B        ┆ 986      ┆ 94     ┆ 7745           ┆ 1499         │
│ 2026-07-12 15:13:59 ┆ B        ┆ 994      ┆ 86     ┆ 7791           ┆ 1453         │
│ 2026-07-12 18:01:35 ┆ B        ┆ 972      ┆ 108    ┆ 5374           ┆ 3870         │
│ 2026-07-12 19:18:45 ┆ B        ┆ 599      ┆ 481    ┆ 2523           ┆ 6721         │
│ 2026-07-12 19:22:38 ┆ B        ┆ 571      ┆ 509    ┆ 2365           ┆ 6879         │
│ …                   ┆ …        ┆ …        ┆ …      ┆ …              ┆ …            │
│ 2026-08-01 12:00:36 ┆ B        ┆ 984      ┆ 96     ┆ 6220           ┆ 3024         │
│ 2026-08-01 12:30:37 ┆ B        ┆ 998      ┆ 82     ┆ 6607           ┆ 2637         │
│ 2026-08-01 13:00:39 ┆ B        ┆ 985      ┆ 95     ┆ 6740           ┆ 2504         │
│ 2026-08-01 13:30:32 ┆ B        ┆ 992      ┆ 88     ┆ 7097           ┆ 2147         │
│ 2026-08-01 14:00:44 ┆ B        ┆ 983      ┆ 97     ┆ 7215           ┆ 2029         │
└─────────────────────┴──────────┴──────────┴────────┴────────────────┴──────────────┘

In [17]:
subset_df  = df.filter(pl.col("car_park") == "B").sort("retrieved_at")

In [18]:
subset_df

shape: (1_183, 6)
┌─────────────────────┬──────────┬──────────┬────────┬────────────────┬──────────────┐
│ retrieved_at        ┆ car_park ┆ occupied ┆ vacant ┆ total_occupied ┆ total_vacant │
│ ---                 ┆ ---      ┆ ---      ┆ ---    ┆ ---            ┆ ---          │
│ datetime[μs]        ┆ str      ┆ i64      ┆ i64    ┆ i64            ┆ i64          │
╞═════════════════════╪══════════╪══════════╪════════╪════════════════╪══════════════╡
│ 2026-07-12 14:44:24 ┆ B        ┆ 986      ┆ 94     ┆ 7745           ┆ 1499         │
│ 2026-07-12 15:13:59 ┆ B        ┆ 994      ┆ 86     ┆ 7791           ┆ 1453         │
│ 2026-07-12 18:01:35 ┆ B        ┆ 972      ┆ 108    ┆ 5374           ┆ 3870         │
│ 2026-07-12 19:18:45 ┆ B        ┆ 599      ┆ 481    ┆ 2523           ┆ 6721         │
│ 2026-07-12 19:22:38 ┆ B        ┆ 571      ┆ 509    ┆ 2365           ┆ 6879         │
│ …                   ┆ …        ┆ …        ┆ …      ┆ …              ┆ …            │
│ 2026-08-01 12:00:36 ┆ B        ┆ 984      ┆ 96     ┆ 6220           ┆ 3024         │
│ 2026-08-01 12:30:37 ┆ B        ┆ 998      ┆ 82     ┆ 6607           ┆ 2637         │
│ 2026-08-01 13:00:39 ┆ B        ┆ 985      ┆ 95     ┆ 6740           ┆ 2504         │
│ 2026-08-01 13:30:32 ┆ B        ┆ 992      ┆ 88     ┆ 7097           ┆ 2147         │
│ 2026-08-01 14:00:44 ┆ B        ┆ 983      ┆ 97     ┆ 7215           ┆ 2029         │
└─────────────────────┴──────────┴──────────┴────────┴────────────────┴──────────────┘

In [23]:
chart = xy.line_chart(
    xy.line(subset_df["retrieved_at"], subset_df["occupied"], color="#7c3aed", width=3)
    , title="Available Spaces in Car Park B Over Time",
    
    )

In [21]:
type(chart)

xy.components.Chart

In [24]:

html = chart.to_html()          # if supported
# or: chart.to_html("carpark_b.html")

from pathlib import Path
Path("carpark_b.html").write_text(html, encoding="utf-8")

426540

In [ ]:

.plot.line(x="retrieved_at", y="occupied", title="Available Spaces in Car Park B Over Time", xlabel="Time", ylabel="Available Spaces")
plot

In [ ]:
plot = df.hvplot.line(
    x="retrieved_at", 
    y="occupied", 
    by="car_park",
    title="Occupancy by Car Park", 
    xlabel="Time", 
    ylabel="Occupied Spaces",
    height=600,
    width=800,
    legend="top_left")
    #responsive=True)
plot

In [ ]:
df

In [ ]:
(df
.group_by(by="retrieved_at")
.agg(pl.sum("occupied")
.alias("total_occupied"))
.sort("total_occupied"))

In [ ]:
plot = (df
.group_by(by="retrieved_at")
.agg(pl.sum("occupied")
.alias("total_occupied"))
.sort("total_occupied")
).hvplot.line(
    x="by", 
    y="total_occupied", 
    title="Total Occupancy Across All Car Parks", 
    xlabel="Time", 
    ylabel="Total Occupied Spaces",
    height=600,
    width=800,
    legend="top_left")

plot